# Generated by Django 6.0.1 on 2026-01-28 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattel', '0005_receta_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('pasos', models.TextField()),
                ('tiempo', models.CharField(default='30 minutos', max_length=50)),
                ('dificultad', models.CharField(default='Fácil', max_length=20)),
                ('tipo', models.CharField(default='ensalada', max_length=50)),
                ('ingredientes', models.TextField(help_text='JSON con ingredientes utilizados')),
                ('origen', models.CharField(choices=[('ia', 'IA (Gemini)'), ('offline', 'Generada Offline'), ('bd', 'De Base de Datos')], default='offline', max_length=10)),
                ('fecha_guardada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Notas personales sobre la receta')),
                ('favorita', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_guardadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recetas Guardadas',
                'ordering': ['-fecha_guardada'],
            },
        ),
    ]
