# Generated by Django 6.0.1 on 2026-01-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mattel', '0006_recetaguardada'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Login',
                'verbose_name_plural': 'Auditorías de Login',
                'ordering': ['-timestamp'],
            },
        ),
    ]
